# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/movies
Accept: application/json

###

GET http://127.0.0.1:8000/movies/1
Accept: application/json

###

POST http://127.0.0.1:8000/movies
Content-Type: application/json

{
  "title": "Batman Begins",
  "year": 2005,
  "director": "Christopher Nolan",
  "description": ""
}

###

DELETE http://127.0.0.1:8000/movies/11
Accept: application/json

###

GET http://127.0.0.1:8000/actor/
Accept: application/json

###

GET http://127.0.0.1:8000/movies/99
Accept: application/json

###

GET http://127.0.0.1:8000/actors/
Accept: application/json

###

GET http://127.0.0.1:8000/actors/1
Accept: application/json

###

POST http://127.0.0.1:8000/actors
Content-Type: application/json

{
  "name": "Donald",
  "surname": "Trump"
}

###

DELETE http://127.0.0.1:8000/actors/4
Accept: application/json

###

POST http://127.0.0.1:8000/actors
Content-Type: application/json

{
  "name": "Donald",
  "surname": "Trump",
  "movie" : ""
}

###